const {
  generateLLMResponse,
} = require("./llmProviderService");

// ==================================================
// Demo AI Fallback
// ==================================================

const generateDemoAIResponse = (text) => {
  return {
    provider: "Demo AI (Fallback)",
    model: "privacy-firewall-local",
    response:
      "I received the protected request successfully. " +
      "The Privacy Firewall processed the input and protected sensitive information " +
      "before AI processing. This response was generated by the local Demo AI fallback " +
      "because the external LLM provider was unavailable.",
  };
};

// ==================================================
// LLM Security Gateway
// ==================================================

const forwardToLLM = async ({
  text,
  llmAllowed,
  decision,
}) => {
  // ==================================================
  // Validate text
  // ==================================================

  if (typeof text !== "string") {
    throw new TypeError(
      "LLM request text must be a string"
    );
  }

  // ==================================================
  // Validate firewall permission
  // ==================================================

  if (typeof llmAllowed !== "boolean") {
    throw new TypeError(
      "llmAllowed must be a boolean"
    );
  }

  // ==================================================
  // Validate firewall decision
  // ==================================================

  if (!decision) {
    throw new Error(
      "Firewall decision is required"
    );
  }

  // ==================================================
  // BLOCKED REQUEST
  // ==================================================

  if (
    decision === "BLOCK" ||
    llmAllowed === false
  ) {
    return {
      forwarded: false,
      blocked: true,

      provider:
        "Privacy Firewall",

      model:
        "Policy Engine",

      requestText:
        text,

      response:
        "Request blocked by the Privacy Firewall. " +
        "The protected payload was not forwarded to any LLM.",

      reason:
        "Privacy policy blocked this request",

      message:
        "Request was stopped before reaching the LLM",
    };
  }

  // ==================================================
  // ALLOWED / PROTECTED REQUEST
  // ==================================================

  try {
    console.log(
      "[LLM Gateway] Forwarding protected request..."
    );

    const llmResult =
      await generateLLMResponse(text);

    // ==================================================
    // Validate Provider Response
    // ==================================================

    if (
      !llmResult ||
      typeof llmResult.response !== "string"
    ) {
      throw new Error(
        "Invalid response received from LLM provider"
      );
    }

    console.log(
      "[LLM Gateway] Real LLM response received"
    );

    return {
      forwarded: true,
      blocked: false,

      provider:
        llmResult.provider || "External LLM",

      model:
        llmResult.model || "Unknown",

      requestText:
        text,

      response:
        llmResult.response,

      message:
        "Protected request was forwarded to the LLM",
    };
  } catch (error) {
    // ==================================================
    // REAL LLM FAILED → DEMO AI FALLBACK
    // ==================================================

    console.warn(
      "[LLM Gateway] External LLM unavailable:",
      error.message
    );

    console.log(
      "[LLM Gateway] Using Demo AI fallback"
    );

    const demoResult =
      generateDemoAIResponse(text);

    return {
      forwarded: true,
      blocked: false,

      provider:
        demoResult.provider,

      model:
        demoResult.model,

      requestText:
        text,

      response:
        demoResult.response,

      message:
        "Protected request was processed by the local Demo AI fallback because the external LLM provider was unavailable.",

      fallback: true,

      fallbackReason:
        error.message,
    };
  }
};

module.exports = {
  forwardToLLM,
};